spring:
  application:
    name: post-service

server:
  port: 8011
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info