spring:
  application:
    name: post-service
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev

server:
  port: 8011
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus
