spring:
  application:
    name: post-service
  config:
    import: optional:configserver:${CENTRAL_CONFIG}:http://localhost:8888
  profiles:
    active: local

server:
  port: 8011
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
