spring:
  application:
    name: post-service
  config:
    import: optional:configserver:${CENTRAL_CONFIG:http://localhost:8888}
  profiles:
    active: local
  zipkin:
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
    enabled: true
  sleuth:
    sampler:
#      percentage: 1.0
      probability: 1.0
  cloud:
    config:
      fail-fast: true
      username: username
      password: password
  security:
    user:
      name: post
      password: password

server:
  port: 8011
  error:
    include-stacktrace: never

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    root: info
    web: debug
    org.springframework.cloud.config: DEBUG
    java.net: trace