spring:
  application:
    name: timeline-service

server:
  port: 8013

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    root: info
