spring:
  application:
    name: timeline-service
  config:
    import: optional:configserver:${CENTRAL_CONFIG:http://localhost:8888}
  profiles:
    active: local

server:
  port: 8013

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    root: info

timeline:
  client:
    post:
      user: post
      password: password