spring:
  application:
    name: gateway
  config:
    import: optional:configserver:${CENTRAL_CONFIG:http://localhost:8888}
  zipkin:
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
    enabled: true
  sleuth:
    sampler:
#      percentage: 1.0
      probability: 1.0

server:
  port: 8890

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    web: debug
    org.springframework.cloud.config: DEBUG
    java.net: trace
    org.springframework.web.client: trace