spring:
  application:
    name: gateway
  config:
    import: optional:configserver:${CENTRAL_CONFIG:http://localhost:8888}

server:
  port: 8890

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
