server:
  port: 8888

spring:
  application:
    name: central-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/claudiomarpda/spring-microservice-template-config

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug