server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: central-config
  security:
    user:
      name: username
      password: password
  cloud:
    config:
#      allowOverride: false
#      overrideNone: true
      server:
#        native:
#          searchLocations: file:C:\Users\...\spring-microservice-template-config
#        search-paths: {application}
        git:
#          uri: file:C:\Users\..\spring-microservice-template-config
#          clone-on-start: false
          uri: https://github.com/claudiomarpda/spring-microservice-template-config

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
